### ISSUE TITLE
[Bug]: Unable to spawn in from the lobby

### ISSUE THREAD

**Issue by Xtrem46** [Naval-Warfare-Remastered/Bug-Reports#13]
### Describe the bug

After match loads, when you click to spawn into the match it doesn't work. 

### Frequency

Usually after match finishes loading. 

### Contact

xtrem46#2098

### Where did this occur?

Test Server

**Comment by plainenglishh** [comment]
this is because players are not allowed to enter the field after the match has ended and is not a bug.
