### ISSUE TITLE
[Bug]: On spawn of a ship/plane, buttons can display the wrong value

### ISSUE THREAD

**Issue by checkraisefold** [Naval-Warfare-Remastered/Bug-Reports#14]
### Describe the bug

For example, throttle and steer lock are on by default, but the buttons will display "OFF"

### Frequency

Every time I use a ship or plane

### Contact

checkraisefold#0001

### Where did this occur?

Development Server

**Comment by plainenglishh** [comment]
duplicate of https://github.com/Naval-Warfare-Remastered/Bug-Reports/issues/10
