### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kynnyck** [Naval-Warfare-Remastered/Bug-Reports#22]
### Describe the bug

The aiming guide over affects the aim and isn't accurate. You are able to spawn vehicles on uncaptured islands, pilots dont die when plane dies (can happen with ships too)

### Frequency

All the time

### Contact

Kynnyck#0413

### Where did this occur?

Development Server

**Comment by checkraisefold** [comment]
Duplicate #15, should just increase scope of #15 to include planes which also have odd aiming behavior

**Comment by plainenglishh** [comment]
One bug per report and include titles. its a mess to deal with these reports when we cant see what theyre about.
