### ISSUE TITLE
[Performance]: Audio issues and Performance for loading map

### ISSUE THREAD

**Issue by Kynnyck** [Naval-Warfare-Remastered/Bug-Reports#25]
### Attach a screenshot of the debug stats and describe your computers specs here.

I was unable to get the screenshot but Audio issues of no audio (I presume there are too many sounds at once), Delayed audio from firing full battery.
Performance after a game when it unloads and loads the map is pretty major and I recommend adding a loading screen.

### Did you experience poor performance in game?

Yes

**Comment by plainenglishh** [comment]
it clearly says to take a screenshot of ur debug stats man
