### ISSUE TITLE
[Suggestion]: Plane Spawn Jank

### ISSUE THREAD

**Issue by LordSuperSucc** [Naval-Warfare-Remastered/Bug-Reports#26]
### Describe your suggestion

When spawning a plane, it always janks out and rams into a wall or something after the engine fully powers up, maybe just lock the plane in a fixed position for a couple seconds and then once airborne, then let the player have full steering control.

### Use Cases and Rationale

You won't get stuck in a wall when you just wanna fly a plane.

### Contact

Der PoopenFarten#4406

**Comment by plainenglishh** [comment]
Merged with #21
