### ISSUE TITLE
[Bug]: Kills not counted in game

### ISSUE THREAD

**Issue by Mustang2049** [Naval-Warfare-Remastered/Bug-Reports#30]
### Describe the bug

After destroying a vehicle, the kill is not counted. This is evident by the leaderboard.

Step to reproduce: Destroy a vehicle using another vehicle.
Expected result: You get a kill.
Actual result: No kills are counted.

Leaderboard during test session:
![nokills](https://user-images.githubusercontent.com/38600514/153736417-33a36144-b619-47ae-b2d3-cce7871825b4.png)
https://user-images.githubusercontent.com/38600514/153736420-59288212-4068-4191-9338-03db24a157bc.mp4

### Frequency

Every time a kill is scored

### Contact

mustang#3083

### Where did this occur?

Development Server

**Comment by checkraisefold** [comment]
owned + no positive kdr for you + ratio

**Comment by plainenglishh** [comment]
Not a bug, feature is in-development.
