### ISSUE TITLE
[Suggestion]: Add a back button to the game select screen

### ISSUE THREAD

**Issue by Mustang2049** [Naval-Warfare-Remastered/Bug-Reports#31]
### Describe your suggestion

Currently, there is no back button from the server selection screen in the launcher.
![nbb](https://user-images.githubusercontent.com/38600514/153736554-51101e44-9212-45b1-8629-40e2c9c01d49.png)

### Use Cases and Rationale

Not useful for now as there are no other menus; in the future, it will be needed.

### Contact

mustang#3083

**Comment by plainenglishh** [comment]
The launcher is currently EOL at the moment and will not be featuring in the prototype release.
