### ISSUE TITLE
[Bug]: Plane hitboxes

### ISSUE THREAD

**Issue by s425265** [Naval-Warfare-Remastered/Bug-Reports#33]
### Describe the bug

> **Bug Title: Plane hitbox **
> **Bug Description: The plane hitbox sempt much larger than the plane itself, and I kept on getting stuck on the bunker. Also had a mid-air collision when I wasn't near another plane. **
> **Reproducible: **Yes
> **Steps to Reproduce: Spawn plane on an island, get semi-close to the bunker (not appearing to touch it) and attempt to takeoff. **
> **Expected Result: Wing hitbox will clip the hangar, not allowing you to takeoff **
> **Actual Result: Same as above... **
> **Platform: PC **
> **Version: Windows 10 **
> **Attachments: none available **

### Frequency

Only a few times, but all happened in the same server

### Contact

bruhpoopmr75#9937

### Where did this occur?

Development Server

**Comment by plainenglishh** [comment]
For future reports please do not use the old formats, Mustang's previous report shows how reports should be formatted:  #9

**Comment by plainenglishh** [comment]
Merged with #21
