### ISSUE TITLE
[Suggestion]: Make the runways a bit longer

### ISSUE THREAD

**Issue by PointyMctest** [Naval-Warfare-Remastered/Bug-Reports#34]
### Describe your suggestion

Found it hard trying to land on the runways with the spitfire as the scale is off the runway is about twice the size of the plane making landings possibly but not realistic nor easy.

### Use Cases and Rationale

when the island is busy the runway will be busy so the longer the better

### Contact

Discord: PointyMctest2#7442

**Comment by EletricalFuse** [comment]
The current map we are using for testing was meant as a temporary map, I just need to wait for plainenglish to incorporate the new map, whose runways are substantially longer than the contemporary.

**Comment by checkraisefold** [comment]
tester map, close

**Comment by plainenglishh** [comment]
^^

**Comment by PointyMctest** [comment]
ok thanks for explaining
