### ISSUE TITLE
[Suggestion]: Add keyboard shortcuts for all boat/plane functions

### ISSUE THREAD

**Issue by PointyMctest** [Naval-Warfare-Remastered/Bug-Reports#41]
### Describe your suggestion

Would be nice to have keyboard key shortcut for the searchlight, rudder, horn etc.
Plane could have a gear up down key too

### Use Cases and Rationale

because its cool

### Contact

Discord: pointymctest2#7442

**Comment by plainenglishh** [comment]
mf they already do what?
