### ISSUE TITLE
[Bug]: Game hates dive bomber strategy because of camera glitch.

### ISSUE THREAD

**Issue by LordSuperSucc** [Naval-Warfare-Remastered/Bug-Reports#51]
### Describe the bug

When aiming downwards towards a target, the camera spazzes out and rotates like 180 degrees.
Makes it super annoying to line up a shot for a bomb

https://user-images.githubusercontent.com/99555982/154180319-846012b5-a756-46b6-a816-f243f756c241.mp4

.

### Frequency

Everytime

### Contact

Der PoopenFarten#4406

### Where did this occur?

Development Server

**Comment by plainenglishh** [comment]
This bug is related to the roblox engine

**Comment by LordSuperSucc** [comment]
> This bug is related to the roblox engine

and there's absolutely nothing you can do to fix it? but dive bombing tho
