### ISSUE TITLE
[Bug]: Me can spawn plane after die

### ISSUE THREAD

**Issue by LordSuperSucc** [Naval-Warfare-Remastered/Bug-Reports#52]
### Describe the bug

watch video
I spawn plane from lobby after dying next to spawn plane button, should work for ships too

https://user-images.githubusercontent.com/99555982/154183007-8c44ff9c-c9f1-4f44-adc3-3d96c455437d.mp4

.

### Frequency

Everytime

### Contact

Der PoopenFarten#4406

### Where did this occur?

Development Server

**Comment by plainenglishh** [comment]
Already reported
