### ISSUE TITLE
[Bug]: Plane and Camera glitching

### ISSUE THREAD

**Issue by Kynnyck** [Naval-Warfare-Remastered/Bug-Reports#54]
### Describe the bug

If you place your mouse if you are looking straight up/down in certain places, the plane will roll and climb/dive and turn. The camera flicks from one place to another

https://user-images.githubusercontent.com/99556121/154183723-f3ca2912-edc1-4989-8ef4-4d3526cfff8a.mp4

https://user-images.githubusercontent.com/99556121/154183725-9abc6ec5-1160-4e87-a25e-efbfc922fc42.mp4

.

### Frequency

I am able to replicate it 100% of the time

### Contact

Kynnyck#0413

### Where did this occur?

Development Server

**Comment by plainenglishh** [comment]
already reported
