### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by BirderJuan** [Naval-Warfare-Remastered/Bug-Reports#55]
### Describe your suggestion

The spitfire control system is quite annoying and confusing to use, and the angles are too limited
Spawnkill is far too easy to do
Vehicles are too fast for such a tiny map

### Use Cases and Rationale

It would make the game more balanced to have ships not be this fast although its the test cruiser and the next ships will probably be way slower and spitfire is clearly a test too as it doesnt follow the style

### Contact

Birder Juan#3035

**Comment by plainenglishh** [comment]
Duplicate, has no title and includes multiple bugs in the same report.
