### ISSUE TITLE
[Bug]: When Spawning in Axis Harbor you face the wall

### ISSUE THREAD

**Issue by PointyMctest** [Naval-Warfare-Remastered/Bug-Reports#57]
### Describe the bug

When Spawning in Axis Harbor you face the wall, when spawning in allies you face out too sea, Should be out to sea both harbors.

### Frequency

Every time you spawn as axis

### Contact

Discord:pointymctest2#7442

### Where did this occur?

Development Server

**Comment by plainenglishh** [comment]
test map thing.

**Comment by PointyMctest** [comment]
ok good to know though relatively easy to fix i would imagine
