### ISSUE TITLE
[Bug]: Warship gun targetting

### ISSUE THREAD

**Issue by kulot70** [Naval-Warfare-Remastered/Bug-Reports#60]
### Describe the bug

When quickly switching from one gun turret to another, if you fire instantly the moment after you switch turrets the shot will not land where the turret is looking (to the left instead)

### Frequency

Happens occasionally

### Contact

hammoodd#1554

### Where did this occur?

Test Server

**Comment by Derpmasternoob** [comment]
Is this because turrets need time to rotate?

**Comment by plainenglishh** [comment]
intentional behaviour, turrets take time to traverse.
