### ISSUE TITLE
[Bug]: Plane does not land on the three wheels - stays on front two with rear in the air

### ISSUE THREAD

**Issue by PointyMctest** [Naval-Warfare-Remastered/Bug-Reports#62]
### Describe the bug

when landing most of the time the Plane does not land on the three wheels - stays on front two with rear in the air.
![image](https://user-images.githubusercontent.com/99589937/154527621-a1708998-dcae-4b35-a32a-da27b6587736.png)

### Frequency

almost every time I land on an island

### Contact

Discord:pointymctest2#7442

### Where did this occur?

Development Server

**Comment by plainenglishh** [comment]
Duplicate
