### ISSUE TITLE
[Bug]: Ship is spawning with 3 out of 4 battery guns.

### ISSUE THREAD

**Issue by PointyMctest** [Naval-Warfare-Remastered/Bug-Reports#63]
### Describe the bug

Ship is spawning with 3 out of 4 battery guns - i'm sure it was ok a few days ago - only noticed the last couple of days that this is happening:

![image](https://user-images.githubusercontent.com/99589937/154528146-080283c7-f727-45b9-81e2-039a89f78423.png)

### Frequency

every time i spawn a ship

### Contact

Discord: pointymctest2#7442

### Where did this occur?

Development Server

**Comment by plainenglishh** [comment]
Intentional behaviour, the square is the dummy depth charge rack.

**Comment by PointyMctest** [comment]
oh wow I could swear I saw four cannons.......
