### ISSUE TITLE
[Bug]: Uniform.

### ISSUE THREAD

**Issue by MrM0XY** [Naval-Warfare-Remastered/Bug-Reports#70]
### Describe the bug

When I'm joining "Axis" team I have no uniform, just my skin tone.
![IMG-ec6d80da5614b9e6c7169daeec166285-V](https://user-images.githubusercontent.com/99994445/154750770-50c5e4ab-9428-4d33-a127-2cd8a17b8897.jpg)

### Frequency

Every every time when I'm joining.

### Contact

Moxy#0500

### Where did this occur?

Test Server

**Comment by checkraisefold** [comment]
I imagine this might've been a temporary asset loading or clientsided bug, is this replicable?

**Comment by EletricalFuse** [comment]
The german uniform shirt got taken down, so it does not replicate to the player because it is nil
