### ISSUE TITLE
[Bug]: Flying Dutchman

### ISSUE THREAD

**Issue by MrM0XY** [Naval-Warfare-Remastered/Bug-Reports#76]
### Describe the bug

![IMG_3791](https://user-images.githubusercontent.com/99994445/155465901-45c2b508-9953-4459-9cb8-ed380260622b.png)

### Frequency

Every every time.

### Contact

Moxy#0500

### Where did this occur?

Test Server

**Comment by PointyMctest** [comment]
not a bug just the test map is that way

**Comment by checkraisefold** [comment]
#12 duplicate close tester map
